Fix Docker Hub credentials with GitHub secrets

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 env:
-  DOCKERHUB_IMAGE: raniayousfi11/pfe-cnf-app
+  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pfe-cnf-app
 
 jobs:
   test:
@@ -58,13 +58,17 @@ jobs:
       - name: Set short image tag
         run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
 
-      - name: Check Docker Hub token
+      - name: Check Docker Hub credentials
         run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "DOCKERHUB_USERNAME is missing"
+            exit 1
+          fi
           if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
             echo "DOCKERHUB_TOKEN is missing"
             exit 1
           fi
-          echo "Docker Hub token exists"
+          echo "Docker Hub credentials exist"
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -72,7 +76,7 @@ jobs:
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: raniayousfi11
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Build Docker image locally
